### ISSUE TITLE
SSH cli not present

### ISSUE THREAD

**Issue by jpadmin** [geerlingguy/docker-debian12-ansible#7]
Hello ,

I was trying to use your image to run an ansible playbook to run a set of commands over a group of servers and then found that the image does not have ssh client.

`{"msg": "Unable to execute ssh command line on a controller due to: [Errno 2] No such file or directory: b'ssh'"}`

**Comment by geerlingguy** [comment]
Since this is a minimal image meant for testing things as a target via Molecule (more or less), it doesn't contain a lot of utilities that may be helpful in other situations (like SSH). Typically you'd use Ansible's docker connection interacting with this container or just use Molecule. If you need SSH, I would suggest using a Dockerfile to add it on top of this image, or to fork this and have a separate image with that and any other utilities that are required.
